version: '3.8'

services:
  memoryark-nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: memoryark-nginx
    ports:
      - "7001:7001"  # 只暴露 NGINX 代理端口
    volumes:
      # 源代碼映射（開發環境）
      - ./frontend:/app/frontend
      - ./backend:/app/backend
      
      # 配置文件映射
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./supervisord.conf:/etc/supervisor/conf.d/memoryark.conf:ro
      - ./backend/.env.nginx:/app/backend/.env:ro
      
      # 數據持久化
      - memoryark_data:/app/backend/data
      - memoryark_uploads:/app/backend/uploads
      - memoryark_logs:/app/backend/logs
      - nginx_logs:/var/log/nginx
      
      # Node modules 緩存
      - frontend_node_modules:/app/frontend/node_modules
    
    environment:
      - NODE_ENV=development
      - GO_ENV=development
      - PORT=8080  # 後端內部端口
      - NGINX_PORT=7001  # NGINX 對外端口
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7001/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    restart: unless-stopped
    
    # 網絡配置
    networks:
      - memoryark-network

volumes:
  memoryark_data:
    driver: local
  memoryark_uploads:
    driver: local
  memoryark_logs:
    driver: local
  nginx_logs:
    driver: local
  frontend_node_modules:
    driver: local

networks:
  memoryark-network:
    driver: bridge
