version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GIN_MODE=release
      - PORT=8081
      - DATABASE_PATH=/app/data/memoryark.db
      - JWT_SECRET=${JWT_SECRET:-memoryark-secret-key}
      - UPLOAD_PATH=${UPLOAD_PATH:-./uploads}
      - ROOT_ADMIN_EMAIL=${ROOT_ADMIN_EMAIL:-94work.net@gmail.com}
      - ROOT_ADMIN_NAME=${ROOT_ADMIN_NAME:-系統管理員}
      - DEVELOPMENT_MODE=false
      - DEV_AUTO_LOGIN_EMAIL=
      - DEV_BYPASS_AUTH=false
      - DEV_CORS_ENABLED=false
      # 檔案處理和串流匯出配置
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-104857600}  # 100MB
      - MAX_UPLOAD_MEMORY=${MAX_UPLOAD_MEMORY:-33554432}  # 32MB
      - DEDUPLICATION_ENABLED=${DEDUPLICATION_ENABLED:-true}
      - STREAMING_EXPORT_ENABLED=${STREAMING_EXPORT_ENABLED:-true}
      - EXPORT_CLEANUP_INTERVAL=${EXPORT_CLEANUP_INTERVAL:-24h}
      - VIRTUAL_PATH_ENABLED=${VIRTUAL_PATH_ENABLED:-true}
      # 效能優化配置
      - GOMEMLIMIT=${GOMEMLIMIT:-512MiB}
      - GOGC=${GOGC:-100}
      - GOMAXPROCS=${GOMAXPROCS:-2}
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./backend/migrations:/app/migrations:ro  # 只讀掛載遷移腳本
    # 資源限制（適合生產環境）
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.25'
    # 健康檢查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "7"

  nginx:
    image: docker.io/nginx:alpine
    ports:
      - "7001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "7"