version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GIN_MODE=release
      - PORT=8080
      - DATABASE_PATH=/app/data/memoryark.db
      - JWT_SECRET=${JWT_SECRET:-memoryark-secret-key}
      - UPLOAD_PATH=/app/uploads
      - ROOT_ADMIN_EMAIL=${ROOT_ADMIN_EMAIL:-admin@memoryark.org}
      - ROOT_ADMIN_NAME=${ROOT_ADMIN_NAME:-系統管理員}
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "7"

  nginx:
    image: nginx:alpine
    ports:
      - "7001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "7"